language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
jobs:
  include:
    - stage: test
      name: Unit test
      if: branch = QA
      script:
        - echo stage test
        - npm test
    - stage: deploy
      name: Deploy to npm
      if: branch = master
      script:
        - npm test
      before_deploy:
        - npm run build
      after_success:
        - npm run coveralls
      deploy:
        provider: npm
        email: $NPM_MAIL
        api_key: $NPM_TOKEN
        skip_clean: true
