language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
jobs:
  include:
    - stage: test
    on:
      branch: QA
    script:
      - echo "stage test"
      - npm test
    - stage: deploy
    on:
      branch: master
    script:
      - echo "stage deploy"
      - npm test