language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
jobs:
  include:
    - stage: test
    echo: run test
    script: npm test
    - stage: deploy
    on:
      branch: master
    echo: run deploy
    script: dnpm run deploy